### ISSUE TITLE
Error compile with online IDE

### ISSUE THREAD

**Issue by zvikas** [ARMmbed/mbed-os-example-cpu-stats#2]
I got the following error while compiling with online IDE for k64F:

#if !defined(MBED_CPU_STATS_ENABLED) || !defined(DEVICE_LPTICKER) || !defined(DEVICE_SLEEP)
#error [NOT_SUPPORTED] test not supported
#endif

**Comment by theotherjimmy** [comment]
@zvikas I'm pretty sure that's a code snippet from a test. Could you verify that you're not building a test?

**Comment by theotherjimmy** [comment]
@zvikas It would also be helpful if you could provide steps to reproduce.

**Comment by zvikas** [comment]
Simply press “import” from IDE, then select “Click here to import from URL” and copy-paste https://github.com/ARMmbed/mbed-os-example-cpu-stats.git to the Source URI field. Then check oob branch from “Revision” and Compile.

**Comment by 0xc0170** [comment]
I can see that the warning is wrong , it's not test but application. So  rather a message should be - Application requires stats to be enabled, lp ticker , etc.

Second, K64F target supports lp ticker and sleep. Do you enable `MBED_CPU_STATS_ENABLED` flag ? I do not see any mention in the example readme but would assume by default this flag is not enabled.

**Comment by zvikas** [comment]
I didn't modify anything or enabled any new flags. The mbed_app.json contains the MBED_CPU_STATS_ENABLED macro.

**Comment by aashishc1988** [comment]
Mbed lib is pointing to the old hash which doesn't enable LPTICKER feature for K64F. Pointing it to the latest release fixes the issue.

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-590

**Comment by adbridge** [comment]
@aashishc1988 @zvikas  Can this issue be closed now then ?

**Comment by zvikas** [comment]
yes confirmed.
