### ISSUE TITLE
F429ZI not supported?

### ISSUE THREAD

**Issue by pcotret** [ARMmbed/mbed-os-example-cpu-stats#79]
### Description of defect
- Import program in MBed Studio : https://github.com/ARMmbed/mbed-os-example-cpu-stats
- Compile it and got the following error:
```
[Error] main.cpp@21,2: [NOT_SUPPORTED] test not supported
```
Which is related to this part of the code:
```
#if !defined(MBED_CPU_STATS_ENABLED) || !defined(DEVICE_LPTICKER) || !defined(DEVICE_SLEEP)
#error [NOT_SUPPORTED] test not supported
#endif
```
Issue seems similar to https://github.com/ARMmbed/mbed-os-example-cpu-stats/issues/2
It seems I only have the `MBED_CPU_STATS_ENABLED` flag in my case.

#### Target(s) affected by this defect ?
DISCO-F429ZI

#### Toolchain(s) (name and version) displaying this defect ?
ARMC6

#### What version of Mbed-os are you using (tag or sha) ?
MBed OS 6.10.0

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)
Mbed Studio: 1.4.1

#### How is this defect reproduced ?
Tried on two different machines, got the same behavior.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3945*

**Comment by 0xc0170** [comment]
@pcotret What is the version of Mbed OS?

I reviewed flags on the latest master. F429ZI nucleo board should have lp ticker and sleep enabled so the cpu stats if the flag is enabled should compile OK.
